# SPDX-FileCopyrightText: 2023 Ross Patterson <me@rpatterson.net>
#
# SPDX-License-Identifier: MIT

[tool.towncrier]
# https://towncrier.readthedocs.io/en/stable/#quick-start
package = "projectstructure"
package_dir = "src"
name = "project-structure"
directory = "./newsfragments"
